services:
  postgres:
    image: postgres:16
    container_name: etl-postgres
    environment:
      POSTGRES_USER: etl
      POSTGRES_PASSWORD: etl
      POSTGRES_DB: etl_catalog
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_replication_slots=10"
    volumes:
      - etl_pg:/var/lib/postgresql/data

volumes:
  etl_pg:
