global:
  scrape_interval: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'etl-worker'
    static_configs:
      - targets: ['host.docker.internal:9898']
        labels:
          service: 'etl-worker'
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
