//! TypeScript source-connector template. Follows the same
//! `===FILE: <path>===\n<body>\n` block convention as `templates::rust`.

pub const SOURCE_TEMPLATE_TS: &str = r#"===FILE: package.json===
{
  "name": "{{NAME}}",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "bundle": "esbuild src/connector.ts --bundle --format=esm --platform=node --outfile=dist/connector.js --external:platform:connector/host",
    "build": "npm run bundle && jco componentize dist/connector.js --wit wit/source-connector.wit --world-name source-connector -o dist/connector.wasm --disable http",
    "test": "vitest run"
  },
  "devDependencies": {
    "@bytecodealliance/jco": "^1.19.0",
    "@bytecodealliance/componentize-js": "^0.18.0",
    "esbuild": "^0.21.0",
    "typescript": "^5.4.0",
    "vitest": "^1.6.0"
  },
  "dependencies": {
    "apache-arrow": "^15.0.0"
  }
}

===FILE: tsconfig.json===
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ES2022",
    "moduleResolution": "bundler",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "allowSyntheticDefaultImports": true,
    "lib": ["ES2022"],
    "types": []
  },
  "include": ["src/**/*.ts", "tests/**/*.ts"]
}

===FILE: .gitignore===
node_modules/
dist/
*.tsbuildinfo

===FILE: wit/source-connector.wit===
package platform:connector@0.1.0;

interface types {
    enum cursor-kind { int64, timestamp-tz }

    record cursor-value {
        kind: cursor-kind,
        value: string,
    }

    record connection-config {
        url: string,
    }

    record source-config {
        json: string,
    }

    record read-outcome {
        batch-ipc: list<u8>,
        rows: u32,
        new-cursor: option<cursor-value>,
        is-final: bool,
    }

    variant connector-error {
        invalid-config(string),
        source-unavailable(string),
        schema-incompatible(string),
        other(string),
    }
}

interface host {
    enum log-level { trace, debug, info, warn, error }
    log: func(level: log-level, message: string);

    record http-request {
        method: string,
        url: string,
        headers: list<tuple<string, string>>,
        body: option<list<u8>>,
    }
    record http-response {
        status: u16,
        headers: list<tuple<string, string>>,
        body: list<u8>,
    }
    http-fetch: func(request: http-request) -> result<http-response, string>;
}

world source-connector {
    use types.{connection-config, source-config, cursor-value, read-outcome, connector-error};
    import host;
    export discover: func(conn: connection-config, source: source-config) -> result<list<u8>, connector-error>;
    export read-batch: func(
        conn: connection-config,
        source: source-config,
        cursor: option<cursor-value>,
        batch-size: u32,
    ) -> result<read-outcome, connector-error>;
}

===FILE: src/parse.ts===
// Pure data transforms live here. Kept separate from connector.ts so
// vitest can exercise them in plain Node without touching the Wasm
// host imports.

import { Schema, Field, Int64 } from 'apache-arrow';

export function helloSchema(): Schema {
    return new Schema([new Field('id', new Int64(), false)]);
}

===FILE: src/connector.ts===
// {{NAME}} — TypeScript source connector skeleton.
//
// jco componentize bundles this entry + a SpiderMonkey runtime into a
// Component Model component implementing the source-connector world.
// The exports below match the world's exported functions.

import { tableFromArrays, tableToIPC } from 'apache-arrow';
import { helloSchema } from './parse.js';

// Host imports — generated by jco from the WIT.
// @ts-expect-error - resolved by jco at componentize time
import { log, httpFetch } from 'platform:connector/host';

function ipcSchemaBytes(): Uint8Array {
    const t = tableFromArrays({ id: BigInt64Array.from([]) });
    return tableToIPC(t, 'stream');
}

export const discover = (
    _conn: { url: string },
    _source: { json: string },
): { tag: 'ok'; val: Uint8Array } | { tag: 'err'; val: { tag: 'other'; val: string } } => {
    try {
        // helloSchema() validates the schema module is importable.
        helloSchema();
        return { tag: 'ok', val: ipcSchemaBytes() };
    } catch (e) {
        return { tag: 'err', val: { tag: 'other', val: String(e) } };
    }
};

export const readBatch = (
    _conn: { url: string },
    _source: { json: string },
    _cursor: { kind: 'int64' | 'timestamp-tz'; value: string } | undefined,
    _batchSize: number,
): {
    tag: 'ok';
    val: { batchIpc: Uint8Array; rows: number; newCursor: undefined; isFinal: boolean };
} => {
    return {
        tag: 'ok',
        val: {
            batchIpc: ipcSchemaBytes(),
            rows: 0,
            newCursor: undefined,
            isFinal: true,
        },
    };
};

===FILE: tests/parse.test.ts===
import { describe, it, expect } from 'vitest';
import { helloSchema } from '../src/parse.js';

describe('helloSchema', () => {
    it('has a single id column', () => {
        const s = helloSchema();
        expect(s.fields.length).toBe(1);
        expect(s.fields[0].name).toBe('id');
    });
});

===FILE: README.md===
# {{NAME}}

A custom TypeScript source connector for the ETL platform.

## Build & publish

```bash
npm install
platform connector test .
platform connector publish . --registry ./connectors
```

The published artifact lands at `./connectors/{{NAME}}@<version>/component.cwasm`.

## Author guide

- Pure data transforms in `src/parse.ts` — exercised by `vitest`.
- Wasm-facing entry in `src/connector.ts` — exports `discover` and `readBatch`. Uses host imports `log` and `httpFetch` from `platform:connector/host` (resolved by jco at componentize time).
"#;

/// Materialize `SOURCE_TEMPLATE_TS` at `target_dir`, substituting `{{NAME}}`.
pub fn materialize_source_template_typescript(
    target_dir: &std::path::Path,
    name: &str,
) -> anyhow::Result<()> {
    use std::fs;
    if target_dir.exists() {
        anyhow::bail!("{} already exists", target_dir.display());
    }
    fs::create_dir_all(target_dir)?;
    let body = SOURCE_TEMPLATE_TS.replace("{{NAME}}", name);
    let mut current_path: Option<std::path::PathBuf> = None;
    let mut current_buf = String::new();
    let flush =
        |path: Option<&std::path::Path>, buf: &str| -> anyhow::Result<()> {
            if let Some(p) = path {
                let abs = target_dir.join(p);
                if let Some(parent) = abs.parent() {
                    fs::create_dir_all(parent)?;
                }
                let content = buf.trim_end_matches('\n').to_string() + "\n";
                fs::write(abs, content)?;
            }
            Ok(())
        };
    for line in body.lines() {
        if let Some(rest) = line.strip_prefix("===FILE: ") {
            let path = rest.trim_end_matches("===");
            flush(current_path.as_deref(), &current_buf)?;
            current_path = Some(std::path::PathBuf::from(path));
            current_buf.clear();
        } else if current_path.is_some() {
            current_buf.push_str(line);
            current_buf.push('\n');
        }
    }
    flush(current_path.as_deref(), &current_buf)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ts_template_creates_expected_files() {
        let dir = tempfile::tempdir().unwrap();
        let target = dir.path().join("acme-source");
        materialize_source_template_typescript(&target, "acme-source").unwrap();
        assert!(target.join("package.json").exists());
        assert!(target.join("tsconfig.json").exists());
        assert!(target.join("wit/source-connector.wit").exists());
        assert!(target.join("src/connector.ts").exists());
        assert!(target.join("src/parse.ts").exists());
        assert!(target.join("tests/parse.test.ts").exists());
        assert!(target.join(".gitignore").exists());
        assert!(target.join("README.md").exists());

        let pkg = std::fs::read_to_string(target.join("package.json")).unwrap();
        assert!(pkg.contains("\"name\": \"acme-source\""));
        assert!(pkg.contains("@bytecodealliance/jco"));

        let connector = std::fs::read_to_string(target.join("src/connector.ts")).unwrap();
        assert!(connector.contains("export const discover"));
        assert!(connector.contains("export const readBatch"));
    }

    #[test]
    fn ts_template_refuses_existing_dir() {
        let dir = tempfile::tempdir().unwrap();
        let target = dir.path().join("acme");
        std::fs::create_dir_all(&target).unwrap();
        let err = materialize_source_template_typescript(&target, "acme").unwrap_err();
        assert!(format!("{err}").contains("already exists"));
    }
}
